name: forecast_dev
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.0.9
  - matplotlib=3.8.2
  - numpy=1.19.2
  - pandas=2.1.4
  - pip=23.3.1
  - pytest=7.4.3
  - python=3.11
  - scipy=1.11.4
  - seaborn=0.13.0
  - statsmodels=0.14.0
  - pip:
    - scikit-learn==1.3.2
    - joblib==1.3.2
    - pytest-cov==4.1.0
    - forecast-tools==0.1.7

