name: forecast_dev
channels:
  - conda-forge
dependencies:
  - hatch
  - joblib=1.4.2
  - jupyterlab=4.2.4
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip=24.0
  - pytest=8.3.2
  - pytest-cov=5.0.0
  - python=3.11
  - scipy=1.14.0
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - scikit-learn=1.5.1
  - pip:
    - forecast-tools==0.2.1

